services:
  symfony-php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: symfony-php
    volumes:
      - .:/var/www/symfony
    networks:
      - symfony-network

  symfony-nginx:
    image: nginx:alpine
    container_name: symfony-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/symfony
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - symfony-php
    networks:
      - symfony-network

  symfony-db:
    image: mysql:8.0
    container_name: symfony-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - symfony-db-data:/var/lib/mysql
    networks:
      - symfony-network

volumes:
  symfony-db-data:

networks:
  symfony-network:
    driver: bridge